"""empty message

Revision ID: 7009ff2e8b3c
Revises: 
Create Date: 2019-10-11 09:56:31.759312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7009ff2e8b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_pretrained', sa.Boolean(), nullable=True),
    sa.Column('is_neural', sa.Boolean(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('institution', sa.String(length=64), nullable=True),
    sa.Column('citation', sa.String(length=256), nullable=True),
    sa.Column('ss_cb513_3', sa.Float(), nullable=True),
    sa.Column('ss_ts115_3', sa.Float(), nullable=True),
    sa.Column('ss_casp12_3', sa.Float(), nullable=True),
    sa.Column('ss_cb513_8', sa.Float(), nullable=True),
    sa.Column('ss_ts115_8', sa.Float(), nullable=True),
    sa.Column('ss_casp12_8', sa.Float(), nullable=True),
    sa.Column('cp_medium_long_pl5', sa.Float(), nullable=True),
    sa.Column('cp_short_range_auprc', sa.Float(), nullable=True),
    sa.Column('cp_short_range_pl', sa.Float(), nullable=True),
    sa.Column('cp_short_range_pl2', sa.Float(), nullable=True),
    sa.Column('cp_short_range_pl5', sa.Float(), nullable=True),
    sa.Column('cp_medium_range_auprc', sa.Float(), nullable=True),
    sa.Column('cp_medium_range_pl', sa.Float(), nullable=True),
    sa.Column('cp_medium_range_pl2', sa.Float(), nullable=True),
    sa.Column('cp_medium_range_pl5', sa.Float(), nullable=True),
    sa.Column('cp_long_range_auprc', sa.Float(), nullable=True),
    sa.Column('cp_long_range_pl', sa.Float(), nullable=True),
    sa.Column('cp_long_range_pl2', sa.Float(), nullable=True),
    sa.Column('cp_long_range_pl5', sa.Float(), nullable=True),
    sa.Column('rh_fold_1', sa.Float(), nullable=True),
    sa.Column('rh_fold_5', sa.Float(), nullable=True),
    sa.Column('rh_superfamily_1', sa.Float(), nullable=True),
    sa.Column('rh_superfamily_5', sa.Float(), nullable=True),
    sa.Column('rh_family_1', sa.Float(), nullable=True),
    sa.Column('rh_family_5', sa.Float(), nullable=True),
    sa.Column('fl_mse_full', sa.Float(), nullable=True),
    sa.Column('fl_rho_full', sa.Float(), nullable=True),
    sa.Column('fl_mse_bright', sa.Float(), nullable=True),
    sa.Column('fl_rho_bright', sa.Float(), nullable=True),
    sa.Column('fl_mse_dark', sa.Float(), nullable=True),
    sa.Column('fl_rho_dark', sa.Float(), nullable=True),
    sa.Column('st_rho', sa.Float(), nullable=True),
    sa.Column('st_acc', sa.Float(), nullable=True),
    sa.Column('st_aaa_rho', sa.Float(), nullable=True),
    sa.Column('st_aaa_acc', sa.Float(), nullable=True),
    sa.Column('st_abba_rho', sa.Float(), nullable=True),
    sa.Column('st_abba_acc', sa.Float(), nullable=True),
    sa.Column('st_babb_rho', sa.Float(), nullable=True),
    sa.Column('st_babb_acc', sa.Float(), nullable=True),
    sa.Column('st_bbabb_rho', sa.Float(), nullable=True),
    sa.Column('st_bbabb_acc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_entry_cp_long_range_auprc'), 'leaderboard_entry', ['cp_long_range_auprc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_long_range_pl'), 'leaderboard_entry', ['cp_long_range_pl'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_long_range_pl2'), 'leaderboard_entry', ['cp_long_range_pl2'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_long_range_pl5'), 'leaderboard_entry', ['cp_long_range_pl5'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_medium_long_pl5'), 'leaderboard_entry', ['cp_medium_long_pl5'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_medium_range_auprc'), 'leaderboard_entry', ['cp_medium_range_auprc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_medium_range_pl'), 'leaderboard_entry', ['cp_medium_range_pl'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_medium_range_pl2'), 'leaderboard_entry', ['cp_medium_range_pl2'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_medium_range_pl5'), 'leaderboard_entry', ['cp_medium_range_pl5'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_short_range_auprc'), 'leaderboard_entry', ['cp_short_range_auprc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_short_range_pl'), 'leaderboard_entry', ['cp_short_range_pl'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_short_range_pl2'), 'leaderboard_entry', ['cp_short_range_pl2'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_cp_short_range_pl5'), 'leaderboard_entry', ['cp_short_range_pl5'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_fl_mse_bright'), 'leaderboard_entry', ['fl_mse_bright'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_fl_mse_dark'), 'leaderboard_entry', ['fl_mse_dark'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_fl_mse_full'), 'leaderboard_entry', ['fl_mse_full'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_fl_rho_bright'), 'leaderboard_entry', ['fl_rho_bright'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_fl_rho_dark'), 'leaderboard_entry', ['fl_rho_dark'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_fl_rho_full'), 'leaderboard_entry', ['fl_rho_full'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_institution'), 'leaderboard_entry', ['institution'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_is_neural'), 'leaderboard_entry', ['is_neural'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_is_pretrained'), 'leaderboard_entry', ['is_pretrained'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_name'), 'leaderboard_entry', ['name'], unique=True)
    op.create_index(op.f('ix_leaderboard_entry_rh_family_1'), 'leaderboard_entry', ['rh_family_1'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_rh_family_5'), 'leaderboard_entry', ['rh_family_5'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_rh_fold_1'), 'leaderboard_entry', ['rh_fold_1'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_rh_fold_5'), 'leaderboard_entry', ['rh_fold_5'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_rh_superfamily_1'), 'leaderboard_entry', ['rh_superfamily_1'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_rh_superfamily_5'), 'leaderboard_entry', ['rh_superfamily_5'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_ss_casp12_3'), 'leaderboard_entry', ['ss_casp12_3'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_ss_casp12_8'), 'leaderboard_entry', ['ss_casp12_8'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_ss_cb513_3'), 'leaderboard_entry', ['ss_cb513_3'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_ss_cb513_8'), 'leaderboard_entry', ['ss_cb513_8'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_ss_ts115_3'), 'leaderboard_entry', ['ss_ts115_3'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_ss_ts115_8'), 'leaderboard_entry', ['ss_ts115_8'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_aaa_acc'), 'leaderboard_entry', ['st_aaa_acc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_aaa_rho'), 'leaderboard_entry', ['st_aaa_rho'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_abba_acc'), 'leaderboard_entry', ['st_abba_acc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_abba_rho'), 'leaderboard_entry', ['st_abba_rho'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_acc'), 'leaderboard_entry', ['st_acc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_babb_acc'), 'leaderboard_entry', ['st_babb_acc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_babb_rho'), 'leaderboard_entry', ['st_babb_rho'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_bbabb_acc'), 'leaderboard_entry', ['st_bbabb_acc'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_bbabb_rho'), 'leaderboard_entry', ['st_bbabb_rho'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_st_rho'), 'leaderboard_entry', ['st_rho'], unique=False)
    op.create_index(op.f('ix_leaderboard_entry_submission_date'), 'leaderboard_entry', ['submission_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_entry_submission_date'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_rho'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_bbabb_rho'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_bbabb_acc'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_babb_rho'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_babb_acc'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_acc'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_abba_rho'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_abba_acc'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_aaa_rho'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_st_aaa_acc'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_ss_ts115_8'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_ss_ts115_3'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_ss_cb513_8'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_ss_cb513_3'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_ss_casp12_8'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_ss_casp12_3'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_rh_superfamily_5'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_rh_superfamily_1'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_rh_fold_5'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_rh_fold_1'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_rh_family_5'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_rh_family_1'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_name'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_is_pretrained'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_is_neural'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_institution'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_fl_rho_full'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_fl_rho_dark'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_fl_rho_bright'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_fl_mse_full'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_fl_mse_dark'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_fl_mse_bright'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_short_range_pl5'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_short_range_pl2'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_short_range_pl'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_short_range_auprc'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_medium_range_pl5'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_medium_range_pl2'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_medium_range_pl'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_medium_range_auprc'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_medium_long_pl5'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_long_range_pl5'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_long_range_pl2'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_long_range_pl'), table_name='leaderboard_entry')
    op.drop_index(op.f('ix_leaderboard_entry_cp_long_range_auprc'), table_name='leaderboard_entry')
    op.drop_table('leaderboard_entry')
    op.drop_table('display_name')
    # ### end Alembic commands ###
