"""re-add DisplayName

Revision ID: b56646369cd2
Revises: 7009ff2e8b3c
Create Date: 2019-10-11 14:18:13.539170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56646369cd2'
down_revision = '7009ff2e8b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_display_name_display_name'), 'display_name', ['display_name'], unique=False)
    op.create_index(op.f('ix_display_name_key_name'), 'display_name', ['key_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_display_name_key_name'), table_name='display_name')
    op.drop_index(op.f('ix_display_name_display_name'), table_name='display_name')
    # ### end Alembic commands ###
